TT_LANGLE = "LANGLE"
TT_RANGLE = "RANGLE"
TT_FWDSLSH = "FWDSLSH"
TT_EQL = "EQL"

TT_STRING = "STRING"
TT_NUMBER = "NUMBER"
TT_WORD = "WORD"

TT_SPACE = "SPACE"
TT_NL = "NEWLINE"
TT_EOF = "EOF"

NUMS = "1234567890"